// Code generated by cmd/refcount: DO NOT EDIT.

//go:build !js

package wgpu

/*
	#include <wgpu.h>
*/
import "C"

import (
	"runtime"
	"sync/atomic"
	"unsafe"
)

type Buffer struct {
	ref    C.WGPUBuffer
	device C.WGPUDevice
	shared bool
}

func (g *Buffer) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *Buffer) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *Buffer) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuBufferRelease(C.WGPUBuffer(ref))
		// release of device is guarded by ref
		C.wgpuDeviceRelease(g.device)
		g.device = nil
	}
}

func (g *Buffer) markShared() {
	g.shared = true
}

type CommandEncoder struct {
	ref    C.WGPUCommandEncoder
	device C.WGPUDevice
	shared bool
}

func (g *CommandEncoder) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *CommandEncoder) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *CommandEncoder) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuCommandEncoderRelease(C.WGPUCommandEncoder(ref))
		// release of device is guarded by ref
		C.wgpuDeviceRelease(g.device)
		g.device = nil
	}
}

func (g *CommandEncoder) markShared() {
	g.shared = true
}

type ComputePassEncoder struct {
	ref    C.WGPUComputePassEncoder
	device C.WGPUDevice
	shared bool
}

func (g *ComputePassEncoder) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *ComputePassEncoder) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *ComputePassEncoder) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuComputePassEncoderRelease(C.WGPUComputePassEncoder(ref))
		// release of device is guarded by ref
		C.wgpuDeviceRelease(g.device)
		g.device = nil
	}
}

func (g *ComputePassEncoder) markShared() {
	g.shared = true
}

type Queue struct {
	ref    C.WGPUQueue
	device C.WGPUDevice
	shared bool
}

func (g *Queue) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *Queue) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *Queue) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuQueueRelease(C.WGPUQueue(ref))
		// release of device is guarded by ref
		C.wgpuDeviceRelease(g.device)
		g.device = nil
	}
}

func (g *Queue) markShared() {
	g.shared = true
}

type RenderPassEncoder struct {
	ref    C.WGPURenderPassEncoder
	device C.WGPUDevice
	shared bool
}

func (g *RenderPassEncoder) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *RenderPassEncoder) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *RenderPassEncoder) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuRenderPassEncoderRelease(C.WGPURenderPassEncoder(ref))
		// release of device is guarded by ref
		C.wgpuDeviceRelease(g.device)
		g.device = nil
	}
}

func (g *RenderPassEncoder) markShared() {
	g.shared = true
}

type Surface struct {
	ref    C.WGPUSurface
	device C.WGPUDevice
	shared bool
}

func (g *Surface) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *Surface) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *Surface) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuSurfaceRelease(C.WGPUSurface(ref))
		// release of device is guarded by ref
		C.wgpuDeviceRelease(g.device)
		g.device = nil
	}
}

func (g *Surface) markShared() {
	g.shared = true
}

type Texture struct {
	ref    C.WGPUTexture
	device C.WGPUDevice
	shared bool
}

func (g *Texture) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *Texture) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *Texture) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuTextureRelease(C.WGPUTexture(ref))
		// release of device is guarded by ref
		C.wgpuDeviceRelease(g.device)
		g.device = nil
	}
}

func (g *Texture) markShared() {
	g.shared = true
}

type Adapter struct {
	ref    C.WGPUAdapter
	shared bool
}

func (g *Adapter) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *Adapter) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *Adapter) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuAdapterRelease(C.WGPUAdapter(ref))
	}
}

func (g *Adapter) markShared() {
	g.shared = true
}

type BindGroup struct {
	ref    C.WGPUBindGroup
	shared bool
}

func (g *BindGroup) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *BindGroup) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *BindGroup) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuBindGroupRelease(C.WGPUBindGroup(ref))
	}
}

func (g *BindGroup) markShared() {
	g.shared = true
}

type BindGroupLayout struct {
	ref    C.WGPUBindGroupLayout
	shared bool
}

func (g *BindGroupLayout) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *BindGroupLayout) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *BindGroupLayout) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuBindGroupLayoutRelease(C.WGPUBindGroupLayout(ref))
	}
}

func (g *BindGroupLayout) markShared() {
	g.shared = true
}

type CommandBuffer struct {
	ref    C.WGPUCommandBuffer
	shared bool
}

func (g *CommandBuffer) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *CommandBuffer) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *CommandBuffer) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuCommandBufferRelease(C.WGPUCommandBuffer(ref))
	}
}

func (g *CommandBuffer) markShared() {
	g.shared = true
}

type ComputePipeline struct {
	ref    C.WGPUComputePipeline
	shared bool
}

func (g *ComputePipeline) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *ComputePipeline) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *ComputePipeline) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuComputePipelineRelease(C.WGPUComputePipeline(ref))
	}
}

func (g *ComputePipeline) markShared() {
	g.shared = true
}

type Device struct {
	ref    C.WGPUDevice
	shared bool
}

func (g *Device) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *Device) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *Device) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuDeviceRelease(C.WGPUDevice(ref))
	}
}

func (g *Device) markShared() {
	g.shared = true
}

type Instance struct {
	ref    C.WGPUInstance
	shared bool
}

func (g *Instance) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *Instance) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *Instance) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuInstanceRelease(C.WGPUInstance(ref))
	}
}

func (g *Instance) markShared() {
	g.shared = true
}

type PipelineLayout struct {
	ref    C.WGPUPipelineLayout
	shared bool
}

func (g *PipelineLayout) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *PipelineLayout) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *PipelineLayout) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuPipelineLayoutRelease(C.WGPUPipelineLayout(ref))
	}
}

func (g *PipelineLayout) markShared() {
	g.shared = true
}

type QuerySet struct {
	ref    C.WGPUQuerySet
	shared bool
}

func (g *QuerySet) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *QuerySet) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *QuerySet) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuQuerySetRelease(C.WGPUQuerySet(ref))
	}
}

func (g *QuerySet) markShared() {
	g.shared = true
}

type RenderBundle struct {
	ref    C.WGPURenderBundle
	shared bool
}

func (g *RenderBundle) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *RenderBundle) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *RenderBundle) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuRenderBundleRelease(C.WGPURenderBundle(ref))
	}
}

func (g *RenderBundle) markShared() {
	g.shared = true
}

type RenderBundleEncoder struct {
	ref    C.WGPURenderBundleEncoder
	shared bool
}

func (g *RenderBundleEncoder) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *RenderBundleEncoder) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *RenderBundleEncoder) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuRenderBundleEncoderRelease(C.WGPURenderBundleEncoder(ref))
	}
}

func (g *RenderBundleEncoder) markShared() {
	g.shared = true
}

type RenderPipeline struct {
	ref    C.WGPURenderPipeline
	shared bool
}

func (g *RenderPipeline) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *RenderPipeline) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *RenderPipeline) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuRenderPipelineRelease(C.WGPURenderPipeline(ref))
	}
}

func (g *RenderPipeline) markShared() {
	g.shared = true
}

type Sampler struct {
	ref    C.WGPUSampler
	shared bool
}

func (g *Sampler) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *Sampler) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *Sampler) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuSamplerRelease(C.WGPUSampler(ref))
	}
}

func (g *Sampler) markShared() {
	g.shared = true
}

type ShaderModule struct {
	ref    C.WGPUShaderModule
	shared bool
}

func (g *ShaderModule) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *ShaderModule) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *ShaderModule) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuShaderModuleRelease(C.WGPUShaderModule(ref))
	}
}

func (g *ShaderModule) markShared() {
	g.shared = true
}

type TextureView struct {
	ref    C.WGPUTextureView
	shared bool
}

func (g *TextureView) IsValid() bool {
	return g != nil && g.ref != nil
}

func (g *TextureView) Release() {
	if g == nil || g.ref == nil {
		return
	}

	// if this is shared, we should not be able to release it manually
	if g.shared {
		return
	}

	// we manually release this object, remove the finalizer, no
	// need to run release on gc again
	runtime.SetFinalizer(g, nil)

	g.release()
}

func (g *TextureView) release() {
	// pointer to the ref field
	ptr := (*unsafe.Pointer)(unsafe.Pointer(&g.ref))

	// get current ref value
	ref := atomic.LoadPointer(ptr)

	// set ref to nil and release instance
	if ref != nil && atomic.CompareAndSwapPointer(ptr, ref, nil) {
		C.wgpuTextureViewRelease(C.WGPUTextureView(ref))
	}
}

func (g *TextureView) markShared() {
	g.shared = true
}
