package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strings"
	"text/template"
)

var nativeTmpl = template.Must(template.New("").Parse(`
	type {{ .Name }} struct {
		ref C.WGPU{{ .Name }}
		{{- if .WithDev }}
		device C.WGPUDevice
		{{- end }}
		shared bool
	}


	func (g *{{ .Name }}) IsValid() bool {
		return g != nil && g.ref != nil
	}

	func (g *{{ .Name }}) Release() {
		if g == nil || g.ref == nil { return }

		// if this is shared, we should not be able to release it manually
		if g.shared { return }

		// we manually release this object, remove the finalizer, no
		// need to run release on gc again
		runtime.SetFinalizer(g, nil)

		g.release()
	}

	func (g *{{ .Name }}) release() {
		// exchange the pointer with nil
		ref := atomic.SwapPointer((*unsafe.Pointer)(unsafe.Pointer(&g.ref)), nil)
		if ref != nil {
			// release the pointer if we got a non-nil value
			C.wgpu{{ .Name }}Release(C.WGPU{{ .Name }}(ref))

			{{- if .WithDev }}
			// do the same for the device reference
			dev := atomic.SwapPointer((*unsafe.Pointer)(unsafe.Pointer(&g.device)), nil)
			if dev != nil {
				C.wgpuDeviceRelease(C.WGPUDevice(dev))
			}
			{{- end }}
		}
	}

	func (g *{{ .Name }}) markShared() {
		g.shared = true
	}
`))

func main() {
	var out = flag.String("out", ".", "output directory")
	flag.Parse()

	var native, js []string

	native = append(native, "// Code generated by cmd/refcount: DO NOT EDIT.\n")
	native = append(native, "//go:build !js")
	native = append(native, "package wgpu")
	native = append(native, `
		/*
		#include <wgpu.h>
		*/
		import "C"

		import (
			"sync/atomic"
			"unsafe"
			"runtime"
		)
	`)

	js = append(js, "//go:build js")
	js = append(js, "package wgpu")
	js = append(js, `import "syscall/js"`)

	for _, name := range slices.Sorted(slices.Values(os.Args[1:])) {
		var withdev bool

		if name[0] == '+' {
			name = name[1:]
			withdev = true
		}

		var buf strings.Builder
		_ = nativeTmpl.Execute(&buf, map[string]any{
			"Name":    name,
			"WithDev": withdev,
		})

		native = append(native, buf.String())

		js = append(js, fmt.Sprintf(`
			type %[1]s struct {
				jsValue js.Value
			}

			func (g *%[1]s) Release() {
				// no-op, just here to keep api compatibly with native version
			}
		
			func (g *%[1]s) IsValid() bool {
				// as long as the instance is reachable it is valid
				return g != nil
			}

			func (g *%[1]s) toJS() any {
				return g.jsValue
			}

			func (g *%[1]s) markShared() {}

		`, name))

	}

	writeCode(*out+"/gen_types.go", native)
	writeCode(*out+"/gen_types_js.go", js)
}

func writeCode(name string, native []string) {
	source := strings.Join(native, "\n")
	formatted, err := format.Source([]byte(source))
	if err != nil {
		panic(err)
	}

	_ = os.WriteFile(name, formatted, 0644)
}
